import * as fs from 'fs-extra';
import * as path from 'path';

/**
 * Get decision template (DEO v1.0 format)
 */
export function getDecisionTemplate(): string {
  return JSON.stringify({
    schema: 'provenancecode.decision.v1',
    id: '',
    title: '',
    version: 1,
    lifecycle: { state: 'draft' },
    timestamps: { created_at: '' },
    actors: { author: '' },
    outcome: '',
    rationale: '',
    risk: { level: 'low' },
    problem: '',
    tags: []
  }, null, 2);
}

/**
 * Get risk template
 */
export function getRiskTemplate(): string {
  return JSON.stringify({
    schema: 'provenancecode.risk.v2',
    risk_id: '',
    title: '',
    description: '',
    severity: 'medium',
    status: 'open',
    linked_decisions: []
  }, null, 2);
}

/**
 * Get provenance README content
 */
export function getProvenanceReadme(): string {
  return `# ProvenanceCode Records

This directory contains Decision Evidence Objects (DEO v1.0) for this project.

## Structure

- \`/decisions\` - Decision Evidence Objects (DEOs)
- \`/risks\` - Risk records
- \`/schemas\` - JSON schemas for validation
- \`provenance.config.json\` - Configuration

## Usage

### Record a decision

\`\`\`bash
prvc journal add "My decision" --outcome="What we decided" --rationale="Why" --risk-level=low
\`\`\`

### Validate records

\`\`\`bash
npx prvc validate
\`\`\`

### Migrate from g2/v2 format

\`\`\`bash
npx prvc migrate --to-deo
\`\`\`

## AI Integration

If you've installed AI starter packs, check \`/ai\` directory for:
- Cursor rules and prompts
- Claude Code instructions
- Antigravity guidelines

## Documentation

- [ProvenanceCode Standard](https://provenancecode.github.io/ProvenanceCode/)
- [DEO v1.0 Specification](https://provenancecode.github.io/ProvenanceCode/standard/deo/)

---

Generated by ProvenanceCode CLI v2.0.0
`;
}

/**
 * Get Cursor AI rules
 */
export function getCursorRules(appCode: string, area: string): string {
  return `# ProvenanceCode DEO v1.0 Rules for Cursor

## Decision Evidence Object (DEO) Creation

When creating ProvenanceCode decision records:

1. **Use DEO v1.0 Schema**: \`provenancecode.decision.v1\`

2. **ID Format**: \`DEC-${appCode}-${area}-XXXXXXX\` (7-digit sequence)
   - Always auto-increment the sequence number
   - Check existing files to find the next number
   - Or use: \`prvc journal add "Title" --outcome="..." --rationale="..." --risk-level=low\`

3. **Required Fields**:
   - \`schema\`: \`"provenancecode.decision.v1"\`
   - \`id\`: Use format above
   - \`title\`: Brief, descriptive title
   - \`version\`: Integer starting at 1
   - \`lifecycle.state\`: Default to \`"draft"\`
   - \`timestamps.created_at\`: ISO 8601
   - \`actors.author\`: Author email or name
   - \`outcome\`: What was decided
   - \`rationale\`: Why it was decided
   - \`risk.level\`: \`low | medium | high | critical\`

4. **Lifecycle States**: draft | proposed | accepted | rejected | superseded

5. **AI Bot Detection**:
   - Set \`actors.bot\` when creating records via AI (e.g. \`"cursor-ai"\`)

6. **Best Practices**:
   - Always fill in \`rationale\` — this is the most important field
   - Link PRs and issues in \`links.pr\` and \`links.issues\`
   - Use \`problem\` to describe the challenge being solved
   - Keep records atomic and focused

## Risk Record Creation

When creating risk records:

1. **ID Format**: \`RSK-${appCode}-${area}-XXXXXX\`

2. **Severity Levels**: low | medium | high | critical

3. **Status Values**: open | monitoring | mitigated | accepted | closed

4. **Link Decisions**: Use \`linked_decisions\` array to reference related decision IDs

## Important Notes

- ⚠️ Do NOT enforce approval workflows
- ⚠️ Do NOT block PRs based on decision status
- ✅ DO validate JSON schema compliance
- ✅ DO encourage linking related records
- ✅ DO default to "draft" lifecycle state for new records
- ✅ DO set \`actors.bot: "cursor-ai"\` when creating records

## Commands

- Add decision: \`prvc journal add "Title" --outcome="..." --rationale="..." --risk-level=low\`
- Validate: \`npx prvc validate\`
- Check config: \`cat provenance/provenance.config.json\`
`;
}

/**
 * Get Cursor create-decision prompt
 */
export function getCursorCreateDecisionPrompt(): string {
  return `# Create ProvenanceCode Decision Evidence Object (DEO v1.0)

Create a new DEO v1.0-compliant decision record.

## Quickest path (CLI):

\`\`\`bash
prvc journal add "Title" --outcome="What was decided" --rationale="Why" --risk-level=low --bot=cursor-ai
\`\`\`

## Manual Steps:

1. Find the next 7-digit sequence number by checking existing \`DEC-*\` files
2. Use the ID format from \`provenance.config.json\` (id_format block)
3. Create a new JSON file with all required DEO v1.0 fields
4. Validate with: \`npx prvc validate\`

## Template:

\`\`\`json
{
  "schema": "provenancecode.decision.v1",
  "id": "DEC-APP-AREA-0000001",
  "title": "Your decision title",
  "version": 1,
  "lifecycle": { "state": "draft" },
  "timestamps": { "created_at": "<ISO8601>" },
  "actors": { "author": "<email>", "bot": "cursor-ai" },
  "outcome": "What was decided",
  "rationale": "Why this was decided",
  "risk": { "level": "low" },
  "problem": "The problem being solved",
  "tags": []
}
\`\`\`
`;
}

/**
 * Get Cursor create-risk prompt
 */
export function getCursorCreateRiskPrompt(): string {
  return `# Create ProvenanceCode Risk Record

Create a new risk record linked to a DEO.

## Steps:

1. Find the next sequence number by checking existing \`RSK-*\` files
2. Use the ID format from \`provenance.config.json\`
3. Create a new JSON file with all required fields
4. Validate with: \`npx prvc validate\`

## Template:

\`\`\`json
{
  "schema": "provenancecode.risk.v2",
  "risk_id": "RSK-APP-AREA-XXXXXX",
  "title": "Risk title",
  "description": "Detailed risk description",
  "severity": "medium",
  "status": "open",
  "linked_decisions": ["DEC-APP-AREA-0000001"]
}
\`\`\`
`;
}

/**
 * Get Cursor PR review prompt
 */
export function getCursorPRReviewPrompt(): string {
  return `# ProvenanceCode PR Review Checklist

When reviewing PRs that include ProvenanceCode records:

## Validation Checks

- [ ] Run \`npx prvc validate\` and check for errors
- [ ] Verify decision/risk IDs follow the format
- [ ] Confirm schema URLs are correct
- [ ] Check all required fields are present

## Quality Checks

- [ ] Decision context is clear and complete
- [ ] Consequences are documented
- [ ] Risks are assessed
- [ ] Related PRs/issues are linked
- [ ] Title is descriptive

## What NOT to Check

- ❌ Do NOT enforce approval status
- ❌ Do NOT require specific status transitions
- ❌ Do NOT block based on decision status
- ❌ Do NOT enforce governance workflows

## Remember

The CLI validates structure, not governance.
The ProvenanceCode GitHub App handles enforcement.
`;
}

// ---------------------------------------------------------------------------
// Hook scripts (Cursor + Claude Code)
// ---------------------------------------------------------------------------

/**
 * Returns the Node.js script used as the preToolUse hook for Cursor
 * and the PreToolUse hook for Claude Code.
 *
 * Behaviour:
 *  1. Finds the nearest provenance.config.json (walks up from the file being
 *     edited, or falls back to repo root). Handles monorepo layouts by
 *     searching the whole repo when needed.
 *  2. Reads the last 5 decisions (sorted by mtime) and counts open risks.
 *  3. Returns an `agent_message` so the agent sees current provenance context
 *     before making changes — without blocking any tool call.
 */
export function getProvenanceContextCheckScript(): string {
  return `#!/usr/bin/env node
'use strict';
// prvc-context-check.js — injected by ProvenanceCode DEO v1.0 starter pack
// Fires on preToolUse (Cursor) / PreToolUse (Claude Code) for Write/Shell tools.
// Reads provenance context and returns it as agent_message. Never blocks.

const fs = require('fs');
const path = require('path');

function readStdin() {
  return new Promise(resolve => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });
}

function getRepoRoot() {
  try {
    const { execSync } = require('child_process');
    return execSync('git rev-parse --show-toplevel', { encoding: 'utf8', stdio: ['pipe','pipe','pipe'] }).trim();
  } catch {
    return process.cwd();
  }
}

// Walk up from startDir looking for provenance/provenance.config.json
function findNearestConfig(startDir, repoRoot) {
  let dir = path.resolve(startDir);
  const stop = path.resolve(repoRoot);
  while (true) {
    const candidate = path.join(dir, 'provenance', 'provenance.config.json');
    if (fs.existsSync(candidate)) return candidate;
    if (dir === stop) break;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

// Monorepo: find ALL provenance.config.json files under repoRoot (depth <= 4)
function findAllConfigs(repoRoot) {
  const results = [];
  function walk(dir, depth) {
    if (depth > 4) return;
    let entries;
    try { entries = fs.readdirSync(dir); } catch { return; }
    for (const entry of entries) {
      if (entry === 'node_modules' || entry === '.git' || entry === 'dist') continue;
      const full = path.join(dir, entry);
      let stat;
      try { stat = fs.statSync(full); } catch { continue; }
      if (entry === 'provenance' && stat.isDirectory()) {
        const cfg = path.join(full, 'provenance.config.json');
        if (fs.existsSync(cfg)) { results.push(cfg); continue; }
      }
      if (stat.isDirectory()) walk(full, depth + 1);
    }
  }
  walk(repoRoot, 0);
  return results;
}

function safeReadJson(filePath) {
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch { return null; }
}

function buildContext(configPath, repoRoot) {
  const config = safeReadJson(configPath);
  if (!config) return null;

  const decisionsRel = (config.paths && config.paths.decisions) || 'provenance/decisions';
  const risksRel     = (config.paths && config.paths.risks)     || 'provenance/risks';

  // Paths are relative to the package root (parent of provenance/)
  const packageRoot  = path.dirname(path.dirname(configPath)); // provenance/../
  const decisionsDir = path.resolve(packageRoot, decisionsRel);
  const risksDir     = path.resolve(packageRoot, risksRel);

  const lines = [];

  // Recent decisions — sort by mtime, take 5
  if (fs.existsSync(decisionsDir)) {
    const files = fs.readdirSync(decisionsDir)
      .filter(f => f.endsWith('.json') && f !== 'TEMPLATE.json')
      .map(f => {
        let mtime = 0;
        try { mtime = fs.statSync(path.join(decisionsDir, f)).mtimeMs; } catch {}
        return { f, mtime };
      })
      .sort((a, b) => b.mtime - a.mtime)
      .slice(0, 5)
      .map(x => x.f);

    for (const f of files) {
      const d = safeReadJson(path.join(decisionsDir, f));
      if (!d) continue;
      const id    = d.id || d.decision_id || '?';
      const state = (d.lifecycle && d.lifecycle.state) || d.status || '?';
      const title = d.title || '?';
      lines.push('  • ' + id + ': ' + title + ' [' + state + ']');
    }
  }

  // Open risks
  let openRisks = 0;
  if (fs.existsSync(risksDir)) {
    for (const f of fs.readdirSync(risksDir).filter(x => x.endsWith('.json') && x !== 'TEMPLATE.json')) {
      const r = safeReadJson(path.join(risksDir, f));
      if (r && r.status === 'open') openRisks++;
    }
  }

  if (lines.length === 0 && openRisks === 0) return null;

  const parts = [];
  const label = packageRoot === repoRoot ? '' : ' (' + path.relative(repoRoot, packageRoot) + ')';
  if (lines.length > 0) {
    parts.push('📋 ProvenanceCode' + label + ' — recent decisions:\\n' + lines.join('\\n'));
  }
  if (openRisks > 0) {
    parts.push('⚠️  ' + openRisks + ' open risk(s) in ' + path.relative(repoRoot, risksDir) + '/');
  }
  return parts.join('\\n\\n');
}

async function main() {
  const raw = await readStdin();
  let input = {};
  try { input = JSON.parse(raw); } catch {}

  const repoRoot = getRepoRoot();

  // Extract the file path from the tool input (Cursor and Claude Code both provide it)
  const toolInput = input.tool_input || input.input || {};
  const filePath  = toolInput.path || toolInput.file_path || toolInput.target_file || '';

  let configPath = null;

  if (filePath) {
    const abs = path.isAbsolute(filePath) ? filePath : path.resolve(process.cwd(), filePath);
    configPath = findNearestConfig(path.dirname(abs), repoRoot);
  }

  // Fallback: repo root config
  if (!configPath) {
    const rootCfg = path.join(repoRoot, 'provenance', 'provenance.config.json');
    if (fs.existsSync(rootCfg)) configPath = rootCfg;
  }

  // Monorepo fallback: find all, pick the one with the most recent activity
  let allConfigs = [];
  if (!configPath) {
    allConfigs = findAllConfigs(repoRoot);
    if (allConfigs.length > 0) configPath = allConfigs[0];
  } else {
    allConfigs = [configPath];
  }

  if (!configPath) {
    process.stdout.write(JSON.stringify({ permission: 'allow' }));
    return;
  }

  // In monorepo mode, build context for every package that has a config
  const ctxParts = [];
  for (const cfg of allConfigs) {
    const ctx = buildContext(cfg, repoRoot);
    if (ctx) ctxParts.push(ctx);
  }

  if (ctxParts.length === 0) {
    process.stdout.write(JSON.stringify({ permission: 'allow' }));
    return;
  }

  const footer = '\\n\\nTo record a decision: prvc journal add "Title" --outcome="..." --rationale="..." --risk-level=low --bot=cursor-ai';
  const agentMessage = ctxParts.join('\\n\\n---\\n\\n') + footer;

  process.stdout.write(JSON.stringify({
    permission: 'allow',
    agent_message: agentMessage
  }));
}

main().catch(() => process.stdout.write(JSON.stringify({ permission: 'allow' })));
`;
}

/**
 * Returns the stop-event prompt for the Cursor hooks.json.
 *
 * Uses a prompt hook (not a script) so it works without any external binary.
 * The prompt tells the agent to check if any significant decisions were made
 * and to create a DEO if one is missing. Handles single and monorepo layouts.
 */
export function getCursorSessionEndPrompt(): string {
  return (
    'Before you finish: check whether any significant decisions were made during this session that should be recorded in ProvenanceCode.\n\n' +
    'STEP 1 — Check if provenance.config.json exists anywhere in this repo (single or monorepo). ' +
    'If no ProvenanceCode setup exists, skip everything below.\n\n' +
    'STEP 2 — Look at the decisions folder(s) (from config paths.decisions). ' +
    'Check whether a new DEO v1.0 JSON file was already created or modified this session ' +
    'that documents the key decision(s) made. If yes, skip.\n\n' +
    'STEP 3 — If no DEO was created and the session involved meaningful choices ' +
    '(architecture, tooling, data model, security, significant refactor, dependency selection), ' +
    'run the command below. In a monorepo, run it from the subdirectory that contains the relevant provenance.config.json.\n\n' +
    '  prvc journal add "<Short title>" --outcome="<What was decided>" --rationale="<Why>" --risk-level=<low|medium|high|critical> --bot=cursor-ai\n\n' +
    'SKIP recording if: (a) the session was purely exploratory or read-only, ' +
    '(b) the user explicitly said not to record, or ' +
    '(c) the change was a trivial fix (typo, formatting, minor config tweak).\n\n' +
    'Do NOT create duplicate records. Do NOT invent decisions that were not made.'
  );
}

/**
 * Returns the Cursor .cursor/hooks.json content.
 * Designed to be merged into any existing hooks.json rather than overwrite.
 */
export function buildCursorHooksJson(existing: any): any {
  const updated = JSON.parse(JSON.stringify(existing || { version: 1, hooks: {} }));
  if (!updated.version) updated.version = 1;
  if (!updated.hooks) updated.hooks = {};

  // --- preToolUse: context injection on Write / StrReplace ---
  if (!Array.isArray(updated.hooks.preToolUse)) updated.hooks.preToolUse = [];
  // Remove any existing prvc entry before re-adding
  updated.hooks.preToolUse = updated.hooks.preToolUse.filter(
    (h: any) => !String(h.command || '').includes('prvc-context-check')
  );
  updated.hooks.preToolUse.push({
    command: '.cursor/hooks/prvc-context-check.js',
    matcher: 'Write|StrReplace',
    timeout: 8
  });

  // --- stop: session-end provenance check (prompt hook) ---
  if (!Array.isArray(updated.hooks.stop)) updated.hooks.stop = [];
  updated.hooks.stop = updated.hooks.stop.filter(
    (h: any) => !String(h.prompt || '').includes('ProvenanceCode')
  );
  updated.hooks.stop.push({
    type: 'prompt',
    prompt: getCursorSessionEndPrompt(),
    timeout: 60,
    loop_limit: 1
  });

  return updated;
}

/**
 * Returns the Claude Code PreToolUse hook script (bash wrapper around the
 * shared Node.js context check script). Placed at .claude/hooks/PreToolUse.js
 */
export function getClaudePreToolUseHookScript(): string {
  // Claude Code passes the same JSON-on-stdin contract as Cursor.
  // We reuse the identical Node.js script — just change the bot name in the footer.
  return getProvenanceContextCheckScript().replace(
    '--bot=cursor-ai',
    '--bot=claude-code'
  );
}

/**
 * Returns the Claude Code Stop hook script.
 *
 * On Stop, Claude Code sends a JSON object with {stop_hook_active, transcript}.
 * If no DEO was created this session, we return {"decision":"continue","reason":"..."}
 * which causes Claude to continue with the instruction to create a record.
 */
export function getClaudeStopHookScript(): string {
  return `#!/usr/bin/env node
'use strict';
// prvc-session-end.js — injected by ProvenanceCode DEO v1.0 starter pack
// Fires on Stop (Claude Code). Checks whether a DEO was recorded this session;
// if not, returns {"decision":"continue"} with instructions to create one.

const fs   = require('fs');
const path = require('path');

function readStdin() {
  return new Promise(resolve => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });
}

function getRepoRoot() {
  try {
    const { execSync } = require('child_process');
    return execSync('git rev-parse --show-toplevel', { encoding: 'utf8', stdio: ['pipe','pipe','pipe'] }).trim();
  } catch { return process.cwd(); }
}

// Find all provenance.config.json files (single + monorepo)
function findAllConfigs(repoRoot) {
  const results = [];
  function walk(dir, depth) {
    if (depth > 4) return;
    let entries;
    try { entries = fs.readdirSync(dir); } catch { return; }
    for (const e of entries) {
      if (e === 'node_modules' || e === '.git' || e === 'dist') continue;
      const full = path.join(dir, e);
      let stat;
      try { stat = fs.statSync(full); } catch { continue; }
      if (e === 'provenance' && stat.isDirectory()) {
        const cfg = path.join(full, 'provenance.config.json');
        if (fs.existsSync(cfg)) { results.push(cfg); continue; }
      }
      if (stat.isDirectory()) walk(full, depth + 1);
    }
  }
  walk(repoRoot, 0);
  return results;
}

function safeReadJson(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; }
}

// Returns true if any decision file was created/modified in the last 2 hours
function sessionHasDecision(configPath) {
  const config = safeReadJson(configPath);
  if (!config) return false;
  const decisionsRel = (config.paths && config.paths.decisions) || 'provenance/decisions';
  const pkgRoot      = path.dirname(path.dirname(configPath));
  const decisionsDir = path.resolve(pkgRoot, decisionsRel);
  if (!fs.existsSync(decisionsDir)) return false;

  const twoHoursAgo = Date.now() - 2 * 60 * 60 * 1000;
  return fs.readdirSync(decisionsDir)
    .filter(f => f.endsWith('.json') && f !== 'TEMPLATE.json')
    .some(f => {
      try { return fs.statSync(path.join(decisionsDir, f)).mtimeMs > twoHoursAgo; }
      catch { return false; }
    });
}

// Extract the tool_names used from the transcript to decide if work was substantive
function wasSubstantiveSession(input) {
  const transcript = input.transcript || [];
  const writingTools = new Set(['Write', 'StrReplace', 'Edit', 'MultiEdit', 'Bash', 'Shell']);
  return transcript.some(msg => {
    if (!msg.content) return false;
    const content = Array.isArray(msg.content) ? msg.content : [msg.content];
    return content.some(block =>
      block && block.type === 'tool_use' && writingTools.has(block.name)
    );
  });
}

async function main() {
  const raw = await readStdin();
  let input = {};
  try { input = JSON.parse(raw); } catch {}

  const repoRoot = getRepoRoot();
  const configs  = findAllConfigs(repoRoot);

  // If no provenance setup at all, do nothing
  if (configs.length === 0) {
    process.stdout.write(JSON.stringify({ decision: 'stop' }));
    return;
  }

  // If work was read-only, skip
  if (!wasSubstantiveSession(input)) {
    process.stdout.write(JSON.stringify({ decision: 'stop' }));
    return;
  }

  // If any config already has a recent decision, skip
  if (configs.some(c => sessionHasDecision(c))) {
    process.stdout.write(JSON.stringify({ decision: 'stop' }));
    return;
  }

  // Build the continue instruction
  let cmd = 'prvc journal add "<Short title>" --outcome="<What was decided>" --rationale="<Why>" --risk-level=<low|medium|high|critical> --bot=claude-code';

  // For monorepo: tell Claude which directory to use
  if (configs.length > 1) {
    const dirs = configs.map(c => path.relative(repoRoot, path.dirname(path.dirname(c)))).join(', ');
    cmd = 'Run prvc journal add from the relevant package directory. Available ProvenanceCode roots: ' + dirs + '.\\n  ' + cmd;
  }

  const reason =
    'No ProvenanceCode decision record was created this session, but substantive changes were made. ' +
    'Please record the key decision(s) now if this session involved a meaningful choice ' +
    '(architecture, tooling, data model, security, significant refactor, dependency selection).\\n\\n' +
    cmd + '\\n\\n' +
    'Skip if: (a) only exploratory/read-only work was done, (b) the user asked not to record, ' +
    'or (c) the changes were trivial (typo, formatting).\\n' +
    'Do NOT create duplicate records. After recording (or deciding to skip), respond with a brief summary.';

  process.stdout.write(JSON.stringify({ decision: 'continue', reason }));
}

main().catch(() => process.stdout.write(JSON.stringify({ decision: 'stop' })));
`;
}

// ---------------------------------------------------------------------------
// Pack creation functions
// ---------------------------------------------------------------------------

/**
 * Create Cursor AI starter pack.
 *
 * Installs:
 *  - provenance/ai/cursor/ — rules, prompts (documentation)
 *  - .cursor/hooks.json    — preToolUse context injection + stop session-end
 *  - .cursor/hooks/prvc-context-check.js  — the hook script
 *
 * Merges into any existing .cursor/hooks.json instead of clobbering it.
 */
export function createCursorStarterPack(baseDir: string, appCode: string, area: string): void {
  // 1. Documentation pack (provenance/ai/cursor/)
  const cursorDir = path.join(baseDir, 'provenance', 'ai', 'cursor');
  const promptsDir = path.join(cursorDir, 'prompts');
  fs.ensureDirSync(promptsDir);
  fs.writeFileSync(path.join(cursorDir, 'rules.md'), getCursorRules(appCode, area));
  fs.writeFileSync(path.join(promptsDir, 'create-decision.md'), getCursorCreateDecisionPrompt());
  fs.writeFileSync(path.join(promptsDir, 'create-risk.md'), getCursorCreateRiskPrompt());
  fs.writeFileSync(path.join(promptsDir, 'pr-review.md'), getCursorPRReviewPrompt());

  // 2. Cursor hooks (.cursor/)
  const cursorHooksDir = path.join(baseDir, '.cursor', 'hooks');
  fs.ensureDirSync(cursorHooksDir);

  // Write the context-check script
  const scriptPath = path.join(cursorHooksDir, 'prvc-context-check.js');
  fs.writeFileSync(scriptPath, getProvenanceContextCheckScript());
  try { fs.chmodSync(scriptPath, '755'); } catch {}

  // Merge into hooks.json
  const hooksJsonPath = path.join(baseDir, '.cursor', 'hooks.json');
  let existing: any = { version: 1, hooks: {} };
  if (fs.existsSync(hooksJsonPath)) {
    try { existing = fs.readJsonSync(hooksJsonPath); } catch {}
  }
  const merged = buildCursorHooksJson(existing);
  fs.writeJsonSync(hooksJsonPath, merged, { spaces: 2 });
}

/**
 * Create Claude Code starter pack.
 *
 * Installs:
 *  - provenance/ai/claude/README.md  — documentation
 *  - .claude/hooks/PreToolUse.js     — context injection before file edits
 *  - .claude/hooks/Stop.js           — session-end provenance check
 *  - .claude/hooks/settings.json     — hook registration
 */
export function createClaudeStarterPack(baseDir: string, appCode: string, area: string): void {
  // Documentation pack
  const claudeDir = path.join(baseDir, 'provenance', 'ai', 'claude');

  fs.ensureDirSync(claudeDir);

  // Claude Code lifecycle hooks (.claude/hooks/)
  const claudeHooksDir = path.join(baseDir, '.claude', 'hooks');
  fs.ensureDirSync(claudeHooksDir);

  // PreToolUse hook
  const preToolScript = path.join(claudeHooksDir, 'PreToolUse.js');
  fs.writeFileSync(preToolScript, getClaudePreToolUseHookScript());
  try { fs.chmodSync(preToolScript, '755'); } catch {}

  // Stop hook
  const stopScript = path.join(claudeHooksDir, 'Stop.js');
  fs.writeFileSync(stopScript, getClaudeStopHookScript());
  try { fs.chmodSync(stopScript, '755'); } catch {}

  // Claude Code hooks settings — merge into existing settings.json
  const settingsPath = path.join(baseDir, '.claude', 'settings.json');
  let settings: any = {};
  if (fs.existsSync(settingsPath)) {
    try { settings = fs.readJsonSync(settingsPath); } catch {}
  }
  if (!settings.hooks) settings.hooks = {};

  // PreToolUse: inject context on Write/Edit/Bash tools
  if (!Array.isArray(settings.hooks.PreToolUse)) settings.hooks.PreToolUse = [];
  settings.hooks.PreToolUse = settings.hooks.PreToolUse.filter((h: any) => {
    const hooks: any[] = Array.isArray(h.hooks) ? h.hooks : [];
    return !hooks.some((e: any) => String(e.command || '').includes('prvc'));
  });
  settings.hooks.PreToolUse.push({
    matcher: 'Write|Edit|MultiEdit|Bash',
    hooks: [{ type: 'command', command: 'node .claude/hooks/PreToolUse.js' }]
  });

  // Stop hook
  if (!Array.isArray(settings.hooks.Stop)) settings.hooks.Stop = [];
  settings.hooks.Stop = settings.hooks.Stop.filter((h: any) => {
    const hooks: any[] = Array.isArray(h.hooks) ? h.hooks : [];
    return !hooks.some((e: any) => String(e.command || '').includes('prvc'));
  });
  settings.hooks.Stop.push({
    hooks: [{ type: 'command', command: 'node .claude/hooks/Stop.js' }]
  });

  fs.writeJsonSync(settingsPath, settings, { spaces: 2 });

  const content = `# ProvenanceCode DEO v1.0 - Claude Code Assistant

## Overview

This project uses ProvenanceCode DEO v1.0 for decision evidence tracking.

## Decision Evidence Objects (DEOs)

- **Location**: \`provenance/decisions/\`
- **Format**: \`DEC-${appCode}-${area}-XXXXXXX.json\` (7-digit sequence)
- **Schema**: \`provenancecode.decision.v1\`
- **Default State**: \`draft\`

## Creating a DEO (quickest path)

\`\`\`bash
prvc journal add "Title" --outcome="What was decided" --rationale="Why" --risk-level=low --bot=claude-code
\`\`\`

## Risk Records

- **Location**: \`provenance/risks/\`
- **Format**: \`RSK-${appCode}-${area}-XXXXXX.json\`
- **Default Status**: open

## Your Role

When asked to create decisions or risks:

1. ✅ Generate valid DEO v1.0-compliant JSON
2. ✅ Always fill in \`rationale\` — the most important field
3. ✅ Set \`actors.bot: "claude-code"\` on records you create
4. ✅ Auto-increment 7-digit sequence numbers
5. ✅ Set \`lifecycle.state: "draft"\` by default
6. ✅ Include all required fields

7. ❌ Do NOT enforce approval workflows
8. ❌ Do NOT block or gate PR merges
9. ❌ Do NOT manage governance state

## Commands

- Add decision: \`prvc journal add "Title" --outcome="..." --rationale="..." --risk-level=low\`
- Validate: \`npx prvc validate\`
- View config: \`cat provenance/provenance.config.json\`

## Templates

See \`provenance/decisions/TEMPLATE.json\` for the DEO v1.0 template.
`;
  
  fs.writeFileSync(path.join(claudeDir, 'README.md'), content);
}

/**
 * Create Antigravity starter pack
 */
export function createAntigravityStarterPack(baseDir: string, appCode: string, area: string): void {
  const antigravityDir = path.join(baseDir, 'provenance', 'ai', 'antigravity');

  fs.ensureDirSync(antigravityDir);

  const content = `# ProvenanceCode DEO v1.0 - Antigravity Integration

## Quick Reference

**Decision ID**: \`DEC-${appCode}-${area}-XXXXXXX\` (7-digit)
**Risk ID**: \`RSK-${appCode}-${area}-XXXXXX\`

## Schema

- Decision: \`provenancecode.decision.v1\`
- Risk: \`provenancecode.risk.v2\`

## Lifecycle States

**Decisions**: draft, proposed, accepted, rejected, superseded
**Risks**: open, monitoring, mitigated, accepted, closed

## Required DEO Fields

- \`schema\`, \`id\`, \`title\`, \`version\`, \`lifecycle.state\`
- \`timestamps.created_at\`, \`actors.author\`
- \`outcome\`, \`rationale\`, \`risk.level\`

## Guidelines

1. Use schema \`"provenancecode.decision.v1"\`
2. Auto-increment 7-digit sequence numbers
3. Default \`lifecycle.state\` to \`"draft"\`
4. Always fill in \`rationale\`
5. Set \`actors.bot\` to identify AI authorship

## Validation

\`\`\`bash
npx prvc validate
\`\`\`

## Boundary

This is the OPEN layer - record creation and validation only.
Governance enforcement is handled by the ProvenanceCode GitHub App.
`;
  
  fs.writeFileSync(path.join(antigravityDir, 'GUIDE.md'), content);
}

