import * as fs from 'fs-extra';
import * as path from 'path';

/**
 * Get decision template
 */
export function getDecisionTemplate(): string {
  return JSON.stringify({
    schema: 'provenancecode.decision.v2',
    decision_id: '',
    title: '',
    status: 'draft',
    context: '',
    decision: '',
    consequences: '',
    risk: '',
    links: []
  }, null, 2);
}

/**
 * Get risk template
 */
export function getRiskTemplate(): string {
  return JSON.stringify({
    schema: 'provenancecode.risk.v2',
    risk_id: '',
    title: '',
    description: '',
    severity: 'medium',
    status: 'open',
    linked_decisions: []
  }, null, 2);
}

/**
 * Get provenance README content
 */
export function getProvenanceReadme(): string {
  return `# ProvenanceCode Records

This directory contains ProvenanceCode G2 (v2.0) decision and risk records for this project.

## Structure

- \`/decisions\` - Decision records (ADRs)
- \`/risks\` - Risk records
- \`/schemas\` - JSON schemas for validation
- \`provenance.config.json\` - Configuration

## Usage

### Validate records

\`\`\`bash
npx prvc validate
\`\`\`

### Create a new decision

1. Copy the template from \`/decisions\`
2. Fill in required fields
3. Use the format: \`DEC-{APP}-{AREA}-{SEQ6}.json\`
4. Run validation before committing

### Create a new risk

1. Copy the template from \`/risks\`
2. Fill in required fields
3. Use the format: \`RSK-{APP}-{AREA}-{SEQ6}.json\`
4. Run validation before committing

## AI Integration

If you've installed AI starter packs, check \`/ai\` directory for:
- Cursor rules and prompts
- Claude Code instructions
- Antigravity guidelines

## Documentation

- [ProvenanceCode Standard](https://provenancecode.org)
- [G2 Specification](https://provenancecode.org/g2)

---

Generated by ProvenanceCode CLI v2.0
`;
}

/**
 * Get Cursor AI rules
 */
export function getCursorRules(appCode: string, area: string): string {
  return `# ProvenanceCode G2 Rules for Cursor

## Decision Record Creation

When creating ProvenanceCode decision records:

1. **Use G2 Schema**: All decisions must reference \`https://provenancecode.org/schemas/decision.g2.schema.json\`

2. **ID Format**: \`DEC-${appCode}-${area}-XXXXXX\`
   - Always auto-increment the sequence number
   - Check existing files to find the next number

3. **Required Fields**:
   - \`schema\`: Must be G2 schema URL
   - \`decision_id\`: Use format above
   - \`title\`: Brief, descriptive title
   - \`status\`: Default to "draft"
   - \`context\`: Why this decision is needed
   - \`decision\`: What was decided

4. **Status Values**: draft | proposed | accepted | rejected | deprecated | superseded

5. **Best Practices**:
   - Link PRs and issues in the \`links\` array
   - Document consequences
   - Assess risks
   - Keep records atomic and focused

## Risk Record Creation

When creating risk records:

1. **Use G2 Schema**: \`https://provenancecode.org/schemas/risk.g2.schema.json\`

2. **ID Format**: \`RSK-${appCode}-${area}-XXXXXX\`

3. **Severity Levels**: low | medium | high | critical

4. **Status Values**: open | monitoring | mitigated | accepted | closed

5. **Link Decisions**: Use \`linked_decisions\` array to reference related decision IDs

## Important Notes

- ⚠️ Do NOT enforce approval workflows
- ⚠️ Do NOT block PRs based on decision status
- ✅ DO validate JSON schema compliance
- ✅ DO encourage linking related records
- ✅ DO default to "draft" status for new records

## Commands

- Validate: \`npx prvc validate\`
- Check config: \`cat provenance/provenance.config.json\`
`;
}

/**
 * Get Cursor create-decision prompt
 */
export function getCursorCreateDecisionPrompt(): string {
  return `# Create ProvenanceCode Decision

Create a new G2-compliant decision record.

## Steps:

1. Find the next sequence number by checking existing \`DEC-*\` files
2. Use the ID format from \`provenance.config.json\`
3. Create a new JSON file with:
   - Valid G2 schema reference
   - Properly formatted decision_id
   - Status set to "draft"
   - All required fields populated

4. Validate with: \`npx prvc validate\`

## Template:

\`\`\`json
{
  "schema": "https://provenancecode.org/schemas/decision.g2.schema.json",
  "decision_id": "DEC-APP-AREA-XXXXXX",
  "title": "Your decision title",
  "status": "draft",
  "context": "Why this decision is needed",
  "decision": "What was decided",
  "consequences": "Expected outcomes",
  "risk": "Risk assessment",
  "links": []
}
\`\`\`
`;
}

/**
 * Get Cursor create-risk prompt
 */
export function getCursorCreateRiskPrompt(): string {
  return `# Create ProvenanceCode Risk

Create a new G2-compliant risk record.

## Steps:

1. Find the next sequence number by checking existing \`RSK-*\` files
2. Use the ID format from \`provenance.config.json\`
3. Create a new JSON file with:
   - Valid G2 schema reference
   - Properly formatted risk_id
   - Status set to "open"
   - Appropriate severity level
   - All required fields populated

4. Validate with: \`npx prvc validate\`

## Template:

\`\`\`json
{
  "schema": "https://provenancecode.org/schemas/risk.g2.schema.json",
  "risk_id": "RSK-APP-AREA-XXXXXX",
  "title": "Risk title",
  "description": "Detailed risk description",
  "severity": "medium",
  "status": "open",
  "linked_decisions": []
}
\`\`\`
`;
}

/**
 * Get Cursor PR review prompt
 */
export function getCursorPRReviewPrompt(): string {
  return `# ProvenanceCode PR Review Checklist

When reviewing PRs that include ProvenanceCode records:

## Validation Checks

- [ ] Run \`npx prvc validate\` and check for errors
- [ ] Verify decision/risk IDs follow the format
- [ ] Confirm schema URLs are correct
- [ ] Check all required fields are present

## Quality Checks

- [ ] Decision context is clear and complete
- [ ] Consequences are documented
- [ ] Risks are assessed
- [ ] Related PRs/issues are linked
- [ ] Title is descriptive

## What NOT to Check

- ❌ Do NOT enforce approval status
- ❌ Do NOT require specific status transitions
- ❌ Do NOT block based on decision status
- ❌ Do NOT enforce governance workflows

## Remember

The CLI validates structure, not governance.
The ProvenanceCode GitHub App handles enforcement.
`;
}

/**
 * Create Cursor AI starter pack
 */
export function createCursorStarterPack(baseDir: string, appCode: string, area: string): void {
  const cursorDir = path.join(baseDir, 'provenance', 'ai', 'cursor');
  const promptsDir = path.join(cursorDir, 'prompts');
  
  fs.ensureDirSync(promptsDir);
  
  fs.writeFileSync(path.join(cursorDir, 'rules.md'), getCursorRules(appCode, area));
  fs.writeFileSync(path.join(promptsDir, 'create-decision.md'), getCursorCreateDecisionPrompt());
  fs.writeFileSync(path.join(promptsDir, 'create-risk.md'), getCursorCreateRiskPrompt());
  fs.writeFileSync(path.join(promptsDir, 'pr-review.md'), getCursorPRReviewPrompt());
}

/**
 * Create Claude Code starter pack
 */
export function createClaudeStarterPack(baseDir: string, appCode: string, area: string): void {
  const claudeDir = path.join(baseDir, 'provenance', 'ai', 'claude');
  
  fs.ensureDirSync(claudeDir);
  
  const content = `# ProvenanceCode G2 - Claude Code Assistant

## Overview

This project uses ProvenanceCode G2 (v2.0) for decision and risk tracking.

## Decision Records

- **Location**: \`provenance/decisions/\`
- **Format**: \`DEC-${appCode}-${area}-XXXXXX.json\`
- **Schema**: https://provenancecode.org/schemas/decision.g2.schema.json
- **Default Status**: draft

## Risk Records

- **Location**: \`provenance/risks/\`
- **Format**: \`RSK-${appCode}-${area}-XXXXXX.json\`
- **Schema**: https://provenancecode.org/schemas/risk.g2.schema.json
- **Default Status**: open

## Your Role

When asked to create decisions or risks:

1. ✅ Generate valid G2-compliant JSON
2. ✅ Auto-increment sequence numbers
3. ✅ Set appropriate default status
4. ✅ Include all required fields
5. ✅ Suggest linking related PRs/issues

6. ❌ Do NOT enforce approval workflows
7. ❌ Do NOT block or gate PR merges
8. ❌ Do NOT manage governance state

## Commands

- Validate: \`npx prvc validate\`
- View config: \`cat provenance/provenance.config.json\`

## Templates

See \`provenance/decisions/\` and \`provenance/risks/\` for template files.
`;
  
  fs.writeFileSync(path.join(claudeDir, 'README.md'), content);
}

/**
 * Create Antigravity starter pack
 */
export function createAntigravityStarterPack(baseDir: string, appCode: string, area: string): void {
  const antigravityDir = path.join(baseDir, 'provenance', 'ai', 'antigravity');
  
  fs.ensureDirSync(antigravityDir);
  
  const content = `# ProvenanceCode G2 - Antigravity Integration

## Quick Reference

**Decision ID**: \`DEC-${appCode}-${area}-XXXXXX\`
**Risk ID**: \`RSK-${appCode}-${area}-XXXXXX\`

## Schemas

- Decision: https://provenancecode.org/schemas/decision.g2.schema.json
- Risk: https://provenancecode.org/schemas/risk.g2.schema.json

## Status Values

**Decisions**: draft, proposed, accepted, rejected, deprecated, superseded
**Risks**: open, monitoring, mitigated, accepted, closed

## Guidelines

1. Always use G2 schema URLs
2. Auto-increment sequence numbers
3. Default to "draft" for decisions
4. Default to "open" for risks
5. Link related records via IDs or URLs

## Validation

\`\`\`bash
npx prvc validate
\`\`\`

## Boundary

This is the OPEN layer - record creation and validation only.
Governance enforcement is handled by the ProvenanceCode GitHub App.
`;
  
  fs.writeFileSync(path.join(antigravityDir, 'GUIDE.md'), content);
}

